# Numpy -> Numerical Python
- Python Library
- Mathematical Manipulation
## why Numpy
1. speed 
2. Multi-dimension support
3. Vectorization
4. homogeneous Array


In [ ]:
import numpy as np

In [ ]:
cmd=> pip install numpy

In [6]:
print(np.__version__)

2.5.1


## print(np.__version__)
## Converting Python List to Numpy array
- Syntax: np.array(a)
- dtype - To find Every Element DataType
- Converting python List to numpy array with specific Datatype
- a=np.array(a,dtype=np.int8)
- np.array(a,dtype=str_)

## Typecasting 
- a.astype(np.int32)


In [10]:
a=[1,2,3,4]
print(a)
print(type(a))
a=np.array(a)
print(a)
print(type(a))
print(a.dtype)

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
int64


In [11]:
a=[1,2,3.5,4.7]
print(a)
print(type(a))
a=np.array(a)
print(a)
print(type(a))
print(a.dtype)

[1, 2, 3.5, 4.7]
<class 'list'>
[1.  2.  3.5 4.7]
<class 'numpy.ndarray'>
float64


In [12]:
a=[1,2,3.5,4.7,True]
print(a)
print(type(a))
a=np.array(a)
print(a)
print(type(a))
print(a.dtype)

[1, 2, 3.5, 4.7, True]
<class 'list'>
[1.  2.  3.5 4.7 1. ]
<class 'numpy.ndarray'>
float64


In [13]:
a=[1,2,3.5,4.7,True,"Kavinya"]
print(a)
print(type(a))
a=np.array(a)
print(a)
print(type(a))
print(a.dtype)

[1, 2, 3.5, 4.7, True, 'Kavinya']
<class 'list'>
['1' '2' '3.5' '4.7' 'True' 'Kavinya']
<class 'numpy.ndarray'>
<U32


In [14]:
#datatype

In [16]:
## 8bit => 1 Byte
## 2**8  => 256 ((-128)  -0-   127)

256


# Creating Numpy array with Specific Datatype

In [20]:
a=[10,20,30,40]
print(a)
print(type(a))
a=np.array(a,dtype=np.int8)
print(a)
print(a.dtype)

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
int8


In [21]:
a=[10,20,30,128]
print(a)
print(type(a))
a=np.array(a,dtype=np.int8)
print(a)
print(a.dtype)

[10, 20, 30, 128]
<class 'list'>


OverflowError: Python integer 128 out of bounds for int8

In [22]:
a=[10,-120,-30,-128]
print(a)
print(type(a))
a=np.array(a,dtype=np.int8)
print(a)
print(a.dtype)

[10, -120, -30, -128]
<class 'list'>
[  10 -120  -30 -128]
int8


In [23]:
a=[10,-120,-30,-129]
print(a)
print(type(a))
a=np.array(a,dtype=np.int8)
print(a)
print(a.dtype)

[10, -120, -30, -129]
<class 'list'>


OverflowError: Python integer -129 out of bounds for int8

In [24]:
a=[10,-120,-30,-129]
print(a)
print(type(a))
a=np.array(a,dtype=np.int16)
print(a)
print(a.dtype)

[10, -120, -30, -129]
<class 'list'>
[  10 -120  -30 -129]
int16


# Typecasting
**convert one datatype to another**

In [29]:
a=[15,25,35,45,55]
a=np.array(a)
print(a)
print(a.dtype)
a=a.astype(dtype=np.int8)
print(a.dtype)

[15 25 35 45 55]
int64
int8


In [31]:
a=[15,25,35,45,55]
a=np.array(a)
print(a)
print(a.dtype)
a=a.astype(dtype=np.float16)
print(a)
print(a.dtype)

[15 25 35 45 55]
int64
[15. 25. 35. 45. 55.]
float16


In [32]:
a=[15,25,135,45,155]
a=np.array(a)
print(a)
print(a.dtype)
a=a.astype(dtype=np.int8) # typeconversion
print(a)
print(a.dtype)

# NOTE: 155 - 256 = -101
# 135 - 256 = -121

[ 15  25 135  45 155]
int64
[  15   25 -121   45 -101]
int8


In [33]:
print(256 - 155)

101


In [34]:
a=[-215,25,-205,45,15]
a=np.array(a)
print(a)
print(a.dtype)
a=a.astype(dtype=np.int8) # typeconversion
print(a)
print(a.dtype)
# NOTE: -215+256 = 41
# NOTE: -205+256 = 45

[-215   25 -205   45   15]
int64
[41 25 51 45 15]
int8


In [35]:
print(-215+256)

41
