# Array
- Array is a collection of values stored in a single variable.
- NumPy arrays store data in a fixed size and same data type, so mathematical operations are very fast.

## Types of Arrays¶
- 1D Array (One-Dimensional) ## One row of values.
- 2D Array (Two-Dimensional) ## Rows and columns.
- 3D Array (Three-Dimensional) ## Collection of 2D arrays.
## Rules
- 1D → Same datatype
- 2D → Same number of columns in every row
- 3D → Same rows and columns in every layer
- nD → Every dimension must have a uniform shape

In [4]:
import numpy as np

In [5]:
# create an Array

In [6]:
a=[1,2,3,4,5]
a=np.array(a)
print(a)

[1 2 3 4 5]


In [7]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


In [12]:
a=np.array([[1,2,3,4,5],[6,7,8,9,15]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 15]]


In [14]:
a=np.array([[1,2,3,4,5],[6,7,8,9,15]])
print(a)
print(a.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 15]]
2


In [15]:
a=np.array([[[1,2,3,4,5],[6,7,8,9,15]],[[1,2,3,4,5],[6,7,8,9,15]]])
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 15]]]


In [16]:
a=np.array([[[1,2,3,4,5],[6,7,8,9,15]],[[1,2,3,4,5],[6,7,8,9,15]]])
print(a)
print(a.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 15]]]
3


In [17]:
a=np.array([[[1,2],[3,4]],[[5,6,7],[8,9,0]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [22]:
a=np.zeros(5)
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[0. 0. 0. 0. 0.]
Dimension: 1
Shape:  (5,)


In [23]:
a=np.zeros((3,5))
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Dimension: 2
Shape:  (3, 5)


In [24]:
a=np.zeros((2,3,5))
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
Dimension: 3
Shape:  (2, 3, 5)


In [25]:
a=np.ones(3)
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[1. 1. 1.]
Dimension: 1
Shape:  (3,)


In [26]:
a=np.ones((2,3))
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
Dimension: 2
Shape:  (2, 3)


In [27]:
a=np.ones((4,2,3))
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Dimension: 3
Shape:  (4, 2, 3)


In [29]:
a=np.full(3,5)
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[5 5 5]
Dimension: 1
Shape:  (3,)


In [30]:
a=np.full((5,3),5)
print(a)
print("Dimension:",a.ndim)
print("Shape: ",a.shape)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
Dimension: 2
Shape:  (5, 3)


In [32]:
# in Python
print(list(range(10)))
print(list(range(2,11,2)))
# Syntax:range(start,stop,step)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8, 10]


In [33]:
# Syntax: np.arange(start, stop, step)

a=np.arange(1,12,2)
print(a)

[ 1  3  5  7  9 11]


In [35]:
# np.linspace(start,stop,count_values)	
a=np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [36]:
a=np.linspace(1,100,5)
print(a)

[  1.    25.75  50.5   75.25 100.  ]
