In [2]:
import numpy as np

# Array Attributes
- Additional Information
- like Shape,ndim,size,dtype,itemsize

- Shape [rows * columns]
- ndim [number of Dimension]
- size [Total Element]
- dtype [data type]
- itemsize [Memory used by one element - in bytes ]


In [17]:
a=np.array([1,2,3,4,5],dtype=np.int8)
b=np.array([[1,2,3,4],[5,6,7,8]])
c=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(a)
print(a.shape)
print("Dimension: ",a.ndim)
print("Size: ",a.size)
print("dtype: ",a.dtype)
print(f"itemsize: {a.itemsize} bytes")
print("****************")
print(b)
print(b.shape)
print("Dimension: ",b.ndim)
print("Size: ",b.size)
print("dtype: ",b.dtype)
print("itemsize: ",b.itemsize)
print("****************")
print(c)
print(c.shape)
print("Dimension: ",c.ndim)
print("Size: ",c.size)
print("dtype: ",c.dtype)
print("itemsize: ",c.itemsize)

[1 2 3 4 5]
(5,)
Dimension:  1
Size:  5
dtype:  int8
itemsize: 1 bytes
****************
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
Dimension:  2
Size:  8
dtype:  int64
itemsize:  8
****************
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
(3, 2, 4)
Dimension:  3
Size:  24
dtype:  int64
itemsize:  8


## Some more
- nbytes [total memory used by Array]
- T [Transpose of array ]
- Strides [how much bytes need to jump to reach next element ]
- flags [Array memory information ]
- shape=(row,column) # DeprecationWarning version: 2.5 current:2.5.1

## nbytes

In [22]:
a=np.array([[1,2,3],[4,5,6]],dtype=np.int8)
print(f"{a.nbytes} bytes")

6 bytes


In [23]:
a=np.array([[1,2,3],[4,5,6]],dtype=np.int16)
print(f"{a.nbytes} bytes")

12 bytes


In [26]:
a=np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a)
print(f"{a.nbytes} bytes")

[[1. 2. 3.]
 [4. 5. 6.]]
24 bytes


## T - Transpose

In [35]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.shape)
print("--------------Transpose-------------------")
a=a.T
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
--------------Transpose-------------------
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
(5, 2)


## Strides [how much bytes need to jump to reach next element ]

In [40]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.strides)
# Column change (1 → 2) = 8 bytes
# Row change (1 → 4) = 3 × 8 = 24 bytes

[[1 2 3]
 [4 5 6]]
(24, 8)


In [46]:
a=np.array([[10,20,30,40],[4,5,6,7]],dtype=np.int8)
print(a)
print(a.strides)
# Column change (1 → 2) = 8 bytes
# Row change (1 → 4) = 3 × 8 = 24 bytes

[[10 20 30 40]
 [ 4  5  6  7]]
(4, 1)


## Flags [Array memory information]

In [47]:
a=np.array([1,2,3,4])
print(a.flags) # show memory properties

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



# Shape 
- reshape - change array Shape
- resize - change the shape of an array and its Size
- flatten - Multi dimensional array -> 1D array (return new)
- ravel - Multi dimensional array -> 1D array (return view - it modify original)

# Shape=(...) [Change Shap]


In [51]:
a=np.array([1,2,3,4,5,6,7,8])
print(a) 
a.shape=(2,4)
print(a)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


C:\Users\DELL\AppData\Local\Temp\ipykernel_5500\2946142680.py:3: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape=(2,4)


In [54]:
print(np.__version__)

2.5.1


In [55]:
a=np.array([1,2,3,4,5,6,7,8])
print(a) 
a.shape=(2,3)
print(a)

[1 2 3 4 5 6 7 8]


C:\Users\DELL\AppData\Local\Temp\ipykernel_5500\2728838951.py:3: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape=(2,3)


ValueError: cannot reshape array of size 8 into shape (2,3)

# reshape()
- its change Shape not Data Element
## Syntax : array.reshape(new_shape)
- automatic dimension (-1)
- Missing Dimension = Total Elements ÷ Known Dimension

In [62]:
a=np.array([1,2,3,4,5,6,7,8])
print(a)
print("Shape: ",a.shape)
print("Dimension: ",a.ndim)
a=a.reshape(2,4) # 1D -> 2D
print(a)
print("Shape: ",a.shape)
print("Dimension: ",a.ndim)

[1 2 3 4 5 6 7 8]
Shape:  (8,)
Dimension:  1
[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
Dimension:  2


In [70]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(2,2,2)
print(a)
print("Shape: ",a.shape)
print("Dimension: ",a.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape:  (2, 2, 2)
Dimension:  3


In [71]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(2,2,3)
print(a)
print("Shape: ",a.shape)
print("Dimension: ",a.ndim)

ValueError: cannot reshape array of size 8 into shape (2,2,3)

In [4]:
a=np.array([[1,2,3,4,5,6]])
a=a.reshape(2,-1) # automatic column Calculation
print(a)
print("Shape: ",a.shape)
print("Dimension: ",a.ndim)

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Dimension:  2


In [78]:
a=np.array([[1,2,3,4,5,6,7,8,9]])
a=a.reshape(2,-1)
print(a)
print("Shape: ",a.shape)
print("Dimension: ",a.ndim)

ValueError: cannot reshape array of size 9 into shape (2,newaxis)

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(-1,2) # automatic Row Calculation
print(a)
print("Shape: ",a.shape)
print("Dimension: ",a.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape:  (4, 2)
Dimension:  2


# resize()  [resize() → Shape and number of elements can change

- resize() changes the shape of an array and can also change its size. If the new size is larger, 
- ndarray.resize() fills new elements with 0, 
- while np.resize() repeats the existing elements. If the new size is smaller, extra elements are discarded.
- Syntax:
## array.resize(new_shape) or np.resize(array, new_shape)

In [84]:
a = np.array([1, 2, 3, 4])
a.resize((2, 3))
print(a)

ValueError: cannot resize an array that may be referenced by another object.
It is possible that this is a false positive.
If you are sure that the array is uniquely referenced, set refcheck=False.

In [90]:
a = np.array([1,2,3,4,5,6]) # decrease Size

a.resize((2,2), refcheck=False)

print(a)

[[1 2]
 [3 4]]


In [89]:
a = np.array([1,2,3,4,5,6]) # increase Size

a.resize((2,6), refcheck=False)

print(a)

[[1 2 3 4 5 6]
 [0 0 0 0 0 0]]


In [3]:
a = np.array([1, 2, 3, 4])
b = np.resize(a, (2, 3))

print(a)
print("-------------")
print(b)
print("-------------")
print(a)

[1 2 3 4]
-------------
[[1 2 3]
 [4 1 2]]
-------------
[1 2 3 4]


# Flatten()
- Multidimensional Array => 1D Array
- flatten return copy

In [7]:
a=np.array([[1,2],[3,4]])
b=a.flatten()
print(b)

[1 2 3 4]


In [9]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b=a.flatten()
print(b)

[1 2 3 4 5 6 7 8]


In [21]:
a=np.array([[1,2],[3,4]])
b=a.flatten()
print(b,"\n------------------")

a[0]=100
print(a)
print("-----------------")
print(b)

[1 2 3 4] 
------------------
[[100 100]
 [  3   4]]
-----------------
[1 2 3 4]


# Ravel()
- Multidimensional Array => 1D array
- mostly return 

In [22]:
a=np.array([[1,2],[3,4]])
b=a.ravel()
print(b)
print("-------------")
a[0]=100
print(b)
print("-------------")
print(a)

[1 2 3 4]
-------------
[100 100   3   4]
-------------
[[100 100]
 [  3   4]]
