In [1]:
import numpy as np

# Indexing

In [5]:
a=np.array([10,20,30,40,50])
print(a)
print(a.shape)
print(a.ndim)
print(a[2])

[10 20 30 40 50]
(5,)
1
30


In [6]:
a=np.array([10,20,30,40,50])
print(a)
print(a.shape)
print(a.ndim)
print(a[-1])

[10 20 30 40 50]
(5,)
1
50


# 2 Dimension

In [7]:
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a)
print(a.shape)
print(a.ndim)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
(2, 5)
2


In [9]:
# Get 1st Row
print(a[0])
print("-------------")
# Get 2nd Row 
print(a[1])
print("-------------")
# Get Last Row
print(a[-1])

[10 20 30 40 50]
-------------
[ 60  70  80  90 100]
-------------
[ 60  70  80  90 100]


In [14]:
print("get 90=> ",a[1][3])
print("get 30=> ",a[0][2])
print("get 60=> ",a[1,0])

get 90=>  90
get 30=>  30
get 60=>  60


# Slicing
- Syntax: [start:end:step]

In [17]:
arr=np.array([10,20,30,40,50])
print(arr)


[10 20 30 40 50]


In [23]:
# Begining
print(arr[0:3])
print(arr[:3])
print("--------------")
print(arr[2:5])
print(arr[2:])

[10 20 30]
[10 20 30]
--------------
[30 40 50]
[30 40 50]


In [25]:
print(arr[0:5:2])
print(arr[::-1])

[10 30 50]
[50 40 30 20 10]


In [33]:
arr=np.array([[10,20,50],[30,40,60]])
print(arr)

[[10 20 50]
 [30 40 60]]


In [34]:
print(arr[0])

[10 20 50]


In [35]:
print(arr[:,1])

[20 40]


In [42]:
print(arr[:2,:2])

[[10 20]
 [30 40]]


In [43]:
print(arr[::-1])

[[30 40 60]
 [10 20 50]]


In [46]:
print(arr[:,::-1])

[[50 20 10]
 [60 40 30]]


In [47]:
print(arr[::-1,::-1])

[[60 40 30]
 [50 20 10]]


# Fancy Indexing

In [50]:
a=np.array([10,20,30,40,50,60,70,80])
print(a[[0,1,3]])

[10 20 40]


In [51]:
print(a>50)

[False False False False False  True  True  True]


# Boolean Indexing

In [52]:
print(a[a>50])

[60 70 80]


In [54]:
arr=np.array([1,3,4,5,8,9,7])
print(arr%2==0)

[False False  True False  True False False]


In [55]:
print(arr[arr%2==0])

[4 8]
