In [1]:
import numpy as np

In [2]:
#Aggregation Functions (sum,mean,median,max,min,std,var,argmax)

In [4]:
arr=[1,4,7,9,3]
print(sum(arr))
print(arr)

24
[1, 4, 7, 9, 3]


In [7]:
arr=np.array([1,4,7,9,3])
print(arr)
print(np.sum(arr))


[1 4 7 9 3]
24


In [8]:
arr=np.array([1,4,7,9,3])
print(arr)
print(np.min(arr))

[1 4 7 9 3]
1


In [9]:
arr=np.array([1,4,7,9,3])
print(arr)
print(np.max(arr))

[1 4 7 9 3]
9


In [10]:
arr=np.array([1,4,7,9,3])
print(arr)
print(np.argmax(arr))

[1 4 7 9 3]
3


In [11]:
arr=np.array([1,4,7,9,3])
print(arr)
print(np.argmin(arr))

[1 4 7 9 3]
0


In [16]:
#mean,median,std,var
arr=np.array([1,4,7,9,3,5])
print(np.mean(arr))
print(np.median(arr)) # 1,3,4,5,7,9 => 9/2
print(np.std(arr))
print(np.var(arr))

4.833333333333333
4.5
2.6087459737497545
6.8055555555555545
