In [1]:
#np.random.rand(3) (3,5)
#rand()
#randint()
#arr=np.array([1,2,3,4,5,6],dtype=np.int8) np.random.choice(arr)
# rng = np.random.default_rng() print("RandomFloat:",rng.random())
# colors = ["red", "green", "blue"] rng.choice(colors)
# rng.choice(10, size=5, replace=False)
# rng = np.random.default_rng(seed=42) print(rng.integers(1,10,5))

In [2]:
import numpy as np

In [3]:
np.random.rand(3)

array([0.15692543, 0.04008309, 0.65316821])

In [4]:
np.random.rand(3,5)

array([[0.70590271, 0.84170009, 0.98953749, 0.99660175, 0.69946053],
       [0.60129223, 0.96625142, 0.66977799, 0.56940916, 0.51784347],
       [0.17809684, 0.18292712, 0.7841871 , 0.15432338, 0.40407289]])

In [11]:
np.random.randint(3)

0

In [16]:
arr=np.array([1,2,3,4,5,6],dtype=np.int8) 
np.random.choice(arr)

np.int8(5)

In [17]:
 rng = np.random.default_rng()

In [18]:
colors = ["red", "green", "blue"] 
rng.choice(colors)

np.str_('green')

In [19]:
rng.integers(10)

np.int64(2)

In [24]:
 rng.choice(10, size=10, replace=False)

array([8, 7, 2, 9, 4, 5, 1, 6, 3, 0])

In [26]:
 rng.choice(10, size=11, replace=False)

ValueError: Cannot take a larger sample than population when replace is False

In [25]:
 rng.choice(10, size=11, replace=True)

array([7, 1, 4, 7, 2, 2, 3, 0, 1, 6, 7])