In [1]:
import numpy as np

In [10]:
a=[1,2,3,4]
print(a+2)

TypeError: can only concatenate list (not "int") to list

In [11]:
a=np.array([1,2,3,4])
print(a+2)

[3 4 5 6]


In [16]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
print("Shape",a.shape)
print("Dimension",a.ndim)
print("Addition: \n",a+3)
print("Sub: \n",a-3)
print("Multiplication: \n",a*3)
print("Divide\n",a/3)
print("Floor Dividion\n",a//3)
print("Exponentials\n",a**2)


[[1 2 3]
 [4 5 6]]
Shape (2, 3)
Dimension 2
Addition: 
 [[4 5 6]
 [7 8 9]]
Sub: 
 [[-2 -1  0]
 [ 1  2  3]]
Multiplication: 
 [[ 3  6  9]
 [12 15 18]]
Divide
 [[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]]
Floor Dividion
 [[0 0 1]
 [1 1 2]]
Exponentials
 [[ 1  4  9]
 [16 25 36]]


# Matrix Multiplication

In [21]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A@B)
print("\n",np.matmul(A,B))


[[19 22]
 [43 50]]

 [[19 22]
 [43 50]]


In [23]:
print(np.prod(A))

24
