In [1]:
import numpy as np

In [7]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [8]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
a=[10,20,30]
np.diag(a)

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [11]:
arr=np.array([[10,  5,  30],
       [ 21, 20,  32],
       [ 33,  22, 30]])
print(arr)
np.diag(arr)

[[10  5 30]
 [21 20 32]
 [33 22 30]]


array([10, 20, 30])

In [13]:
arr=np.array([10,5,30,2,35,41])
arr[np.where(arr>10)]

array([30, 35, 41])

In [17]:
arr=np.array([1,2,3,4,5])
print(np.clip(arr, 2, 3))

[2 2 3 3 3]


In [18]:
arr=np.array([1,2,3,4,5]) 
print(np.all(arr > 3))

False


In [19]:
arr=np.array([1,2,3,4,5]) 
print(np.any(arr > 3))

True
