In [1]:
#np.sort()
#print(np.sort(arr)[::-1])
#arr = np.array([[9,2],[5,8],[1,6]]) print(np.sort(arr, axis=0))
#argsort-> arr=np.array([50,20,80,10]) print(np.argsort(arr))
# names=np.array(["A","B","C","D"]) salary=np.array([50000,30000,70000,20000]) idx=np.argsort(salary) print(names[idx])
#----------------------------
# print(np.unique(arr)) # print(np.unique(arr,axis=0))
# duplicate Count=> u,c=np.unique(arr,return_counts=True)
# u,i=np.unique(arr,return_index=True)

In [2]:
import numpy as np

In [6]:
arr=np.array([10,40,20,70,30,60])
print(np.sort(arr))

[10 20 30 40 60 70]


In [8]:
print(np.sort(arr)[::-1])

[70 60 40 30 20 10]


In [15]:
a=np.array([[1,5,3],[7,4,2]])
print(a)
print("After Sorting")
print(np.sort(a, axis=1))

[[1 5 3]
 [7 4 2]]
After Sorting
[[1 3 5]
 [2 4 7]]


In [19]:
names=np.array(["A","B","C","D"]) 
salary=np.array([50000,30000,70000,20000]) 
print(np.argsort(salary))
print(names[idx])

[3 1 0 2]
['D' 'B' 'A' 'C']


In [20]:
arr=np.array([1,2,2,2,3,4,5,5,2,3])
print(np.unique(arr)) # print(np.unique(arr,axis=0))

[1 2 3 4 5]


In [22]:
u,c=np.unique(arr,return_counts=True)
print(u,c)
u,i=np.unique(arr,return_index=True)
print(u,i)

[1 2 3 4 5] [1 4 2 1 2]
[1 2 3 4 5] [0 1 4 5 6]
